# Generated by Django 5.0.6 on 2024-08-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceshop', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roduct_brand', to='ecommerceshop.brand'),
            preserve_default=False,
        ),
    ]
